/** SQL 方言类型 / 关键字粗映射（启发式，非完整 SQL 解析） */

const MAP: Record<string, Record<string, string>> = {
  'mysql->postgres': {
    AUTO_INCREMENT: 'GENERATED BY DEFAULT AS IDENTITY',
    TINYINT: 'SMALLINT',
    DATETIME: 'TIMESTAMP',
    LONGTEXT: 'TEXT',
    MEDIUMTEXT: 'TEXT',
    TINYTEXT: 'TEXT',
    '`': '"',
  },
  'postgres->mysql': {
    'GENERATED BY DEFAULT AS IDENTITY': 'AUTO_INCREMENT',
    SERIAL: 'INT AUTO_INCREMENT',
    TIMESTAMP: 'DATETIME',
    BOOLEAN: 'TINYINT(1)',
  },
  'mysql->oracle': {
    AUTO_INCREMENT: 'GENERATED BY DEFAULT AS IDENTITY',
    DATETIME: 'TIMESTAMP',
    VARCHAR: 'VARCHAR2',
    // MySQL 文本类型 → Oracle CLOB（勿造 LONGCLOB）
    LONGTEXT: 'CLOB',
    MEDIUMTEXT: 'CLOB',
    TINYTEXT: 'CLOB',
    TEXT: 'CLOB',
    TINYINT: 'NUMBER(3)',
    INT: 'NUMBER(10)',
    BIGINT: 'NUMBER(19)',
  },
}

export function sqlDialectConvert(sql: string, from: string, to: string): string {
  const key = from + '->' + to
  const rules = MAP[key]
  if (!rules) return '-- 暂无 ' + key + ' 规则，仅输出原文\n' + sql
  let out = sql
  // 较长 key 优先，避免 TEXT 先于 LONGTEXT 被替换导致 LONGCLOB
  const entries = Object.entries(rules).sort((a, b) => b[0].length - a[0].length)
  for (const [a, b] of entries) {
    out = out.replace(new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), b)
  }
  return '-- converted ' + key + '\n' + out
}

export const SQL_DIALECT_SAMPLE_MYSQL_ORACLE =
  'CREATE TABLE t (\n' +
  '  id INT AUTO_INCREMENT PRIMARY KEY,\n' +
  '  title VARCHAR(200),\n' +
  '  body LONGTEXT,\n' +
  '  summary MEDIUMTEXT,\n' +
  '  note TEXT,\n' +
  '  created DATETIME\n' +
  ');\n'
